version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

jobs:

  deploy_app_container_in_heroku:
    <<: *defaults
    steps:
      - setup_remote_docker:
          # Supported versions: https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.6
      - checkout:
          path: ~/project
      - run:
          name: Build image
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            make build-ml-api-heroku
      - run:
          name: Push Image to Heroku
          command: |
            # Push the built container to the Heroku image registry
            make push-ml-api-heroku
      - run:
          name: Release to Heroku
          command: |
            make release-heroku

workflows:
  version: 2.1
  deploying:
    jobs:
      - deploy_app_container_in_heroku:
          filters:
            branches:
              only:
                - main